import asyncio
import json
import shutil
from typing import Any, Optional

from models.usage import ProviderUsage, UsageCapabilities, UsageWindow
from utils.cli import is_codex_logged_in
from utils.time import now_iso, unix_seconds_to_iso

from .base import UsageProvider


class CodexRpcError(Exception):
    pass


async def _call_rate_limits() -> dict[str, Any]:
    """Spawns `codex app-server --stdio`, performs the JSON-RPC initialize
    handshake, and calls the official `account/rateLimits/read` method.

    This is not a scraped or guessed endpoint: it is generated by Codex's own
    `codex app-server generate-json-schema` command, i.e. Codex's documented
    app-server protocol used internally by its own VS Code/desktop clients.
    """
    binary = shutil.which("codex")
    if binary is None:
        raise CodexRpcError("codex_cli_not_found")

    # `codex` resolves to an npm-installed .CMD shim on Windows; create_subprocess_exec
    # calls CreateProcess directly and does not forward stdio through such shims
    # correctly, so the shell form is used here (mirrors invoking it from a real shell).
    proc = await asyncio.create_subprocess_shell(
        f'"{binary}" app-server --stdio',
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    async def send(msg: dict[str, Any]) -> None:
        assert proc.stdin is not None
        proc.stdin.write((json.dumps(msg) + "\n").encode())
        await proc.stdin.drain()

    async def read_response(expected_id: int) -> dict[str, Any]:
        assert proc.stdout is not None
        while True:
            line = await asyncio.wait_for(proc.stdout.readline(), timeout=10)
            if not line:
                raise CodexRpcError("codex_app_server_closed")
            try:
                msg = json.loads(line.decode())
            except json.JSONDecodeError:
                continue
            if msg.get("id") == expected_id:
                if "error" in msg:
                    raise CodexRpcError(str(msg["error"]))
                return msg.get("result", {})

    try:
        await send(
            {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {"clientInfo": {"name": "ai-usage-monitor", "version": "0.1.0"}},
            }
        )
        await read_response(1)

        await send({"jsonrpc": "2.0", "id": 2, "method": "account/rateLimits/read", "params": None})
        result = await read_response(2)
        return result
    finally:
        # `proc` is the cmd.exe shell wrapper on Windows (codex resolves to a
        # .CMD shim); killing it does not reliably reap the grandchild codex.exe
        # promptly, so cleanup is best-effort and never allowed to block the
        # response we already have.
        try:
            proc.kill()
        except ProcessLookupError:
            pass
        try:
            await asyncio.wait_for(proc.wait(), timeout=3)
        except asyncio.TimeoutError:
            pass


def _window(raw: Optional[dict[str, Any]]) -> Optional[UsageWindow]:
    if raw is None:
        return None
    used = int(raw.get("usedPercent", 0))
    reset_at = None
    if raw.get("resetsAt") is not None:
        reset_at = unix_seconds_to_iso(int(raw["resetsAt"]))
    window_hours = None
    if raw.get("windowDurationMins") is not None:
        window_hours = round(int(raw["windowDurationMins"]) / 60, 2)
    return UsageWindow(
        window_hours=window_hours,
        used_percent=used,
        remaining_percent=max(0, 100 - used),
        reset_at=reset_at,
    )


class CodexSubscriptionProvider(UsageProvider):
    provider_id = "codex"

    async def get_usage(self) -> ProviderUsage:
        try:
            result = await _call_rate_limits()
        except (CodexRpcError, asyncio.TimeoutError, OSError) as exc:
            binary = shutil.which("codex")
            if binary is None or str(exc) == "codex_cli_not_found":
                reason = "codex_cli_not_found"
            elif not await is_codex_logged_in(binary):
                reason = "codex_not_logged_in"
            else:
                reason = "codex_subscription_usage_unavailable"

            return ProviderUsage(
                provider="codex",
                available=False,
                reason=reason,
                usage_source="unavailable",
                capabilities=UsageCapabilities(
                    session_usage=False,
                    weekly_usage=False,
                    reset_time=False,
                    service_status=True,
                ),
                last_updated=now_iso(),
            )

        rate_limits = result.get("rateLimits", {})
        session = _window(rate_limits.get("primary"))
        weekly = _window(rate_limits.get("secondary"))

        return ProviderUsage(
            provider="codex",
            available=True,
            session=session,
            weekly=weekly,
            usage_source="codex_cli",
            capabilities=UsageCapabilities(
                session_usage=session is not None,
                weekly_usage=weekly is not None,
                reset_time=True,
                service_status=True,
            ),
            last_updated=now_iso(),
        )
